// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHvZYBZfLD74Egk6X6f1R0RC5qmqaKLnM',
    appId: '1:398005183283:web:f56eba43ce036c8f485446',
    messagingSenderId: '398005183283',
    projectId: 'calcicfun',
    authDomain: 'calcicfun.firebaseapp.com',
    storageBucket: 'calcicfun.appspot.com',
    measurementId: 'G-0YTCNYFBW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSLWdlgAxj13xBDkUd2H8XJLjVG6AAUMs',
    appId: '1:398005183283:android:59b36d167d3c3dbd485446',
    messagingSenderId: '398005183283',
    projectId: 'calcicfun',
    storageBucket: 'calcicfun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHGoOj8FMC3787BKNv_mXnJk3AEQ8_hWM',
    appId: '1:398005183283:ios:2bf0a504f9dc93c1485446',
    messagingSenderId: '398005183283',
    projectId: 'calcicfun',
    storageBucket: 'calcicfun.appspot.com',
    iosBundleId: 'com.example.cryptoApp',
  );
}
